baseURL = 'https://projects.razonyang.com/hugo-mod-search/'
languageCode = 'en'
title = 'Hugo Search Module'

[[module.imports]]
path = 'github.com/razonyang/hugo-mod-search'

[outputs]
home = ["HTML", "SearchIndex"]

[languages.en]
languageName = "English"

[languages.zh-hans]
languageName = "简体中文"

[languages.zh-hant]
languageName = "繁体中文"

[params.search]
input_placeholder = 'Type to search'
# index_all_pages = false
# expand_results_meta = true
